# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b4 on Mon Mar  4 00:24:41 2019
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class FileTransferFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FileTransferFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((808, 603))
        self.buttonLocalBack = wx.Button(self, wx.ID_ANY, u"\u2190")
        self.buttonLocalUp = wx.Button(self, wx.ID_ANY, u"\u2191")
        self.buttonLoacalRefresh = wx.Button(self, wx.ID_ANY, u"\u27f3")
        self.textLocalDir = wx.TextCtrl(self, wx.ID_ANY, "")
        self.buttonRemoteBack = wx.Button(self, wx.ID_ANY, u"\u2190")
        self.buttonRemoteUp = wx.Button(self, wx.ID_ANY, u"\u2191")
        self.buttonRemoteRefresh = wx.Button(self, wx.ID_ANY, u"\u27f3")
        self.textRemoteDir = wx.TextCtrl(self, wx.ID_ANY, "")
        self.listLocalDir = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT)
        self.listRemoteDir = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT)
        self.buttonUpload = wx.Button(self, wx.ID_ANY, "Upload")
        self.buttonDownload = wx.Button(self, wx.ID_ANY, "Download")
        self.progressBar = wx.Gauge(self, wx.ID_ANY, 1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.localBack_onClick, self.buttonLocalBack)
        self.Bind(wx.EVT_BUTTON, self.localUp_onClick, self.buttonLocalUp)
        self.Bind(wx.EVT_BUTTON, self.localRefresh_onClick, self.buttonLoacalRefresh)
        self.Bind(wx.EVT_TEXT_ENTER, self.localDir_enterPress, self.textLocalDir)
        self.Bind(wx.EVT_BUTTON, self.remoteBack_onClick, self.buttonRemoteBack)
        self.Bind(wx.EVT_BUTTON, self.remoteUp_onClick, self.buttonRemoteUp)
        self.Bind(wx.EVT_BUTTON, self.remoteRefresh_onClick, self.buttonRemoteRefresh)
        self.Bind(wx.EVT_TEXT_ENTER, self.remoteDir_enterPress, self.textRemoteDir)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.listLocalDir_onClick, self.listLocalDir)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.listRemoteDir_onClick, self.listRemoteDir)
        self.Bind(wx.EVT_BUTTON, self.buttonUpload_Click, self.buttonUpload)
        self.Bind(wx.EVT_BUTTON, self.buttonDownload_onClick, self.buttonDownload)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FileTransferFrame.__set_properties
        self.SetTitle("File Transfer")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("./res/remote.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.buttonLocalBack.SetMinSize((35, 35))
        self.buttonLocalBack.SetToolTip("Go back")
        self.buttonLocalUp.SetMinSize((35, 35))
        self.buttonLocalUp.SetToolTip("Go up")
        self.buttonLoacalRefresh.SetMinSize((35, 35))
        self.buttonRemoteBack.SetMinSize((35, 35))
        self.buttonRemoteBack.SetToolTip("Go back")
        self.buttonRemoteUp.SetMinSize((35, 35))
        self.buttonRemoteUp.SetToolTip("Go up")
        self.buttonRemoteRefresh.SetMinSize((35, 35))
        self.listLocalDir.AppendColumn("", format=wx.LIST_FORMAT_LEFT, width=30)
        self.listLocalDir.AppendColumn("File", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.listLocalDir.AppendColumn("Type", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.listRemoteDir.AppendColumn("", format=wx.LIST_FORMAT_LEFT, width=30)
        self.listRemoteDir.AppendColumn("File name", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.listRemoteDir.AppendColumn("Type", format=wx.LIST_FORMAT_LEFT, width=-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FileTransferFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_3 = wx.FlexGridSizer(3, 2, 0, 0)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.buttonLocalBack, 0, 0, 0)
        sizer_2.Add(self.buttonLocalUp, 0, 0, 0)
        sizer_2.Add(self.buttonLoacalRefresh, 0, 0, 0)
        sizer_2.Add(self.textLocalDir, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_3.Add(self.buttonRemoteBack, 0, 0, 0)
        sizer_3.Add(self.buttonRemoteUp, 0, 0, 0)
        sizer_3.Add(self.buttonRemoteRefresh, 0, 0, 0)
        sizer_3.Add(self.textRemoteDir, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.listLocalDir, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.listRemoteDir, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.buttonUpload, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_3.Add(self.buttonDownload, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_3.AddGrowableRow(1)
        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_3.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(self.progressBar, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def localBack_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'localBack_onClick' not implemented!")
        event.Skip()

    def localUp_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'localUp_onClick' not implemented!")
        event.Skip()

    def localRefresh_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'localRefresh_onClick' not implemented!")
        event.Skip()

    def localDir_enterPress(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'localDir_enterPress' not implemented!")
        event.Skip()

    def remoteBack_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'remoteBack_onClick' not implemented!")
        event.Skip()

    def remoteUp_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'remoteUp_onClick' not implemented!")
        event.Skip()

    def remoteRefresh_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'remoteRefresh_onClick' not implemented!")
        event.Skip()

    def remoteDir_enterPress(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'remoteDir_enterPress' not implemented!")
        event.Skip()

    def listLocalDir_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'listLocalDir_onClick' not implemented!")
        event.Skip()

    def listRemoteDir_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'listRemoteDir_onClick' not implemented!")
        event.Skip()

    def buttonUpload_Click(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'buttonUpload_Click' not implemented!")
        event.Skip()

    def buttonDownload_onClick(self, event):  # wxGlade: FileTransferFrame.<event_handler>
        print("Event handler 'buttonDownload_onClick' not implemented!")
        event.Skip()

# end of class FileTransferFrame
