# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b4 on Mon Mar  4 00:24:41 2019
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class FilenameDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FilenameDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.SYSTEM_MENU
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((300, 120))
        self.dTextName = wx.TextCtrl(self, wx.ID_ANY, _(u""))
        self.dButtonOK = wx.Button(self, wx.ID_OK, _(u"OK"))
        self.dButtonCancel = wx.Button(self, wx.ID_CANCEL, _(u"Cancel"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FilenameDialog.__set_properties
        self.SetTitle(_(u"New Key"))
        self.SetSize((300, 120))
        self.dTextName.SetMinSize((120, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FilenameDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        dLabelName = wx.StaticText(self, wx.ID_ANY, _(u"New key file name: "), style=wx.ALIGN_RIGHT)
        dLabelName.SetMinSize((130, 30))
        sizer_2.Add(dLabelName, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.dTextName, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.ALIGN_CENTER, 0)
        sizer_10.Add(self.dButtonOK, 0, 0, 0)
        sizer_10.Add(self.dButtonCancel, 0, 0, 0)
        sizer_1.Add(sizer_10, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class FilenameDialog
