# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b4 on Mon Mar  4 23:59:55 2019
#

import wx
import util.settingread
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SettingFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((384, 298))
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.panel_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.radioBuiltInVNC = wx.RadioButton(self.panel_1, wx.ID_ANY, _(u"Built-in VNC Viewer"))
        self.radioRealVNC = wx.RadioButton(self.panel_1, wx.ID_ANY, _(u"RealVNC Viewer"))
        self.textCtrlVNCPath = wx.TextCtrl(self.panel_1, wx.ID_ANY, _(u""))
        self.buttonVNCPath = wx.Button(self.panel_1, wx.ID_ANY, _(u"Browse..."))
        self.textCtrlRemotePort = wx.TextCtrl(self.panel_1, wx.ID_ANY, _(u""))
        self.notebook_1_Language = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.choiceLanguage = wx.Choice(self.notebook_1_Language, wx.ID_ANY, choices=[_(u"English"), _(u"Chinese (Simplified)"), _(u"Chinese (Traditional)")])
        self.buttonOK = wx.Button(self, wx.ID_ANY, _(u"OK"))
        self.buttonCancel = wx.Button(self, wx.ID_ANY, _(u"Cancel"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_RADIOBUTTON, self.radioBuiltInVNC_selected, self.radioBuiltInVNC)
        self.Bind(wx.EVT_RADIOBUTTON, self.radioRealVNC_selected, self.radioRealVNC)
        self.Bind(wx.EVT_BUTTON, self.buttonVNCPath_onClick, self.buttonVNCPath)
        self.Bind(wx.EVT_BUTTON, self.buttonOK_onClick, self.buttonOK)
        self.Bind(wx.EVT_BUTTON, self.buttonCancel_onClick, self.buttonCancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SettingFrame.__set_properties
        self.SetTitle(_(u"Settings"))
        self.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_MENU))
        self.textCtrlVNCPath.SetMinSize((200, 28))
        self.buttonVNCPath.SetMinSize((88, 28))
        self.textCtrlRemotePort.SetMinSize((70, 28))
        self.choiceLanguage.SetSelection(0)
        self.notebook_1.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_MENU))
        # end wxGlade

        # Windows icon attachment 
        icon = wx.Icon(wx.IconLocation('./res/remote.ico'))
        self.SetIcon(icon)

        

    def __do_layout(self):
        # begin wxGlade: SettingFrame.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(self.radioBuiltInVNC, 0, wx.ALL, 5)
        sizer_11.Add(self.radioRealVNC, 0, wx.ALL, 5)
        sizer_14.Add(self.textCtrlVNCPath, 0, wx.ALL, 5)
        sizer_14.Add(self.buttonVNCPath, 0, wx.ALL, 5)
        sizer_11.Add(sizer_14, 0, wx.BOTTOM, 6)
        portLabel = wx.StaticText(self.panel_1, wx.ID_ANY, _(u"Remote Port:"))
        sizer_17.Add(portLabel, 0, wx.ALL, 4)
        sizer_17.Add(self.textCtrlRemotePort, 0, wx.ALL, 0)
        sizer_11.Add(sizer_17, 1, 0, 0)
        self.panel_1.SetSizer(sizer_11)
        label_2 = wx.StaticText(self.notebook_1_Language, wx.ID_ANY, _(u"Display Language"))
        sizer_18.Add(label_2, 0, wx.ALL, 9)
        sizer_18.Add(self.choiceLanguage, 0, wx.ALL, 5)
        self.notebook_1_Language.SetSizer(sizer_18)
        self.notebook_1.AddPage(self.panel_1, _(u"VNC Viewer"))
        self.notebook_1.AddPage(self.notebook_1_Language, _(u"Language"))
        sizer_4.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_15.Add(self.buttonOK, 0, 0, 0)
        sizer_15.Add(self.buttonCancel, 0, 0, 0)
        sizer_4.Add(sizer_15, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.SHAPED, 0)
        self.SetSizer(sizer_4)
        self.Layout()
        # end wxGlade


    def LoadSetting(self):
        local, real, port = util.settingread.GetVNCSetting()
        lang = int(util.settingread.GetLangSetting())
        if local:
            self.radioBuiltInVNC.SetValue(True)
            self.radioRealVNC.SetValue(False)
            self.buttonVNCPath.Disable()
            self.textCtrlVNCPath.Disable()
        else:
            self.radioBuiltInVNC.SetValue(False)
            self.radioRealVNC.SetValue(True)
            self.buttonVNCPath.Enable()
            self.textCtrlVNCPath.Enable()
        self.textCtrlVNCPath.SetValue(real)
        self.textCtrlRemotePort.SetValue(port)
        self.choiceLanguage.SetSelection(lang)

    def radioBuiltInVNC_selected(self, event):  # wxGlade: SettingFrame.<event_handler>
        self.buttonVNCPath.Disable()
        self.textCtrlVNCPath.Disable()

    def radioRealVNC_selected(self, event):  # wxGlade: SettingFrame.<event_handler>
        self.buttonVNCPath.Enable()
        self.textCtrlVNCPath.Enable()

    def buttonVNCPath_onClick(self, event):  # wxGlade: SettingFrame.<event_handler>
        fileDialog = wx.FileDialog(self, _(u"RealVNC Viewer"), wildcard=_(u"Executable (*.exe)|*.exe"), style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)
        fileDialog.ShowModal()
        pathname = fileDialog.GetPath()
        fileDialog.Destroy()
        self.textCtrlVNCPath.Value = pathname

    def buttonOK_onClick(self, event):  # wxGlade: SettingFrame.<event_handler>
        util.settingread.SetVNCSetting(self.radioBuiltInVNC.GetValue(), self.textCtrlVNCPath.GetValue(), self.textCtrlRemotePort.GetValue())
        util.settingread.SetLangSetting(self.choiceLanguage.GetSelection())
        self.Destroy()

    def buttonCancel_onClick(self, event):  # wxGlade: SettingFrame.<event_handler>
        self.Destroy()
# end of class SettingFrame
